apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: my-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

# IMPORTANTE => Kubernetes no enlaza por nombre sino por características
# ¿Y si hubiera varios PV compatibles?:
#   Kubernetes elegirá uno libre que cumpla las condiciones.
#   Si quieres que el PVC se conecte a un PV específico, puedes usar un selector.