apiVersion: v1
kind: Service
metadata:
  name: nodeport-frontend
  namespace: my-app
spec:
  type: NodePort
  selector:
    pod: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 #Sera accesible desde este puerto expuesto por el nodeport