apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: my-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlwYXNzd29yZA==   # "mypassword" en base64
  MYSQL_PASSWORD: bXl1c2VycGFzcw==       # "myuserpass" en base64